
#Load necessary packages using library(packagename)
```{r}
library(rwhatsapp)
library(ggplot2)
library(tidyr)
library(lubridate)
library(readr)
library(stringr)
library(dplyr)
library(tm)
library(kableExtra)
library(RColorBrewer)
library(knitr)
library(plotly)
library(htmlwidgets)
library(tidyverse)
library(tidytext)
library(wordcloud)
```




```{r}
chat <- rwa_read("/Users/Medasani chaithanya/Documents/chat.txt") %>% 
  filter(!is.na(author)) # remove messages without author

```

```{r}
chat %>%
  mutate(day = date(time)) %>%
  count(day) %>%
  ggplot(aes(x = day, y = n)) +
  geom_bar(stat = "identity", fill = "#52854C") +
  ylab("") + xlab("") +
  ggtitle("Messages per day")
```

```{r}
chat %>%
  unnest_tokens(input = text, output = word) %>%
 
  count(word) %>% 
  # PLOT OF THE TOP 20 MOST USED WORDS IN CONVERSATION
  top_n(30,n) %>% 
  arrange(desc(n)) %>% 
  ggplot(aes(x=reorder(word,n), y=n, fill=n, color=n)) +
  geom_col(show.legend = FALSE, width = .1) +
  geom_point(show.legend = FALSE, size = 3) +
  scale_fill_gradient(low="#2b83ba",high="#d7191c") +
  scale_color_gradient(low="#2b83ba",high="#d7191c") +
  ggtitle("Words most used in conversation in general") +
  xlab("Words") +
  ylab("Number of times the word was used") +
  coord_flip() +
  theme_minimal()
```

```{r}
chat %>%
  mutate(day = date(time)) %>%
  count(author) %>%
  ggplot(aes(x = reorder(author, n), y = n)) +
  geom_bar(stat = "identity",fill = "#52854C") +
  ylab("") + xlab("") +
  coord_flip() +
  ggtitle("Number of messages")
```
Unique words of Karthik
```{r}
o_words <- chat %>%
  unnest_tokens(input = text,
                output = word) %>%
  filter(author != "Karthik") %>% 
  count(word, sort = TRUE) 

chat %>%
  unnest_tokens(input = text,
                output = word) %>%
  filter(author == "Karthik") %>% 
  count(word, sort = TRUE) %>% 
  filter(!word %in% o_words$word) %>% # only select words nobody else uses
  top_n(n = 6, n) %>%
  ggplot(aes(x = reorder(word, n), y = n)) +
  geom_bar(stat = "identity",fill = "#52854C") +
  ylab("") + xlab("") +
  coord_flip() +
  ggtitle("Unique words of Karthik")
```

Most Used Emojis
```{r}
library("tidyr")
chat %>%
  unnest(emoji) %>%
  count(author, emoji, sort = TRUE) %>%
  group_by(author) %>%
  top_n(n = 6, n) %>%
  ggplot(aes(x = reorder(emoji, n), y = n, fill = author)) +
  geom_col(show.legend = FALSE) +
  ylab("") +
  xlab("") +
  coord_flip() +
  facet_wrap(~author, ncol = 2, scales = "free_y")  +
  ggtitle("Most often used emojis")
```
Most Often used Words
```{r}
chat %>%
  unnest_tokens(input = text,
                output = word) %>%
  count(author, word, sort = TRUE) %>%
  group_by(author) %>%
  top_n(n = 6, n) %>%
  ggplot(aes(x = reorder_within(word, n, author), y = n, fill = author)) +
  geom_col(show.legend = FALSE) +
  ylab("") +
  xlab("") +
  coord_flip() +
  facet_wrap(~author, ncol = 2, scales = "free_y") +
  scale_x_reordered() +
  ggtitle("Most often used words")
```
DAYS MOST ACTIVE
```{r}
#DAYS OF WEEK MOST ACTIVE
# Mutate to add a column Dow ( Day of week )
wdata <- chat %>% mutate(Dow =  wday(as.Date(chat$time), label=TRUE))

dow <- wdata %>% filter(Dow !='') %>% group_by(Dow) %>% summarise(count = n())
ggplot(dow,aes(x=Dow,y = count, fill = Dow))+
  geom_bar(stat = "identity")+
  xlab("Days of the week")+
  ylab("Messages")+
  coord_flip()+
  geom_text(aes(label = scales::comma(count)), hjust = 3) +
  ggtitle("Days most active")+
  theme_minimal()
```


WRITTEN WORDS
```{r}
#MEMBER TOTAL WORDS USED
wdata = chat %>% mutate(word_count = sapply(strsplit(chat$text, " "), length))

words <- wdata %>% group_by(author)%>% summarise(count= sum(word_count))
ggplot(words,aes(x=author,y = count, fill = author))+
  geom_bar(stat = "identity")+
  xlab("Days of the week")+
  ylab("Messages")+
  geom_text(size = 3,aes(label = paste0(scales::comma(count), " (",round(count/sum(count)*100,0) ,"%)")), vjust = -1) +
  ggtitle("WRITTEN WORDS")+
  theme_minimal()
```
